name: CI/CD
on:
  push:
    branches:
      - main
      - test_409153
      - documentation_409153
      - cicd_409153
  pull_request:
    branches:
      - main
      - test_409153
      - documentation_409153
      - cicd_409153
permissions:
  contents: read
jobs:
  test-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: x64
      - name: Run tests
        run: python -m unittest
  test-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: x64
      - name: Run tests
        run: python -m unittest
